# Generated by Django 6.0.3 on 2026-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_policy_number_policyholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
