# Generated by Django 6.0.3 on 2026-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_policyholder_maturity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
