# Generated by Django 6.0.3 on 2026-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='policy',
            new_name='policy_number',
        ),
    ]
