# Generated by Django 6.0.3 on 2026-03-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_policy_agent_policy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='policy_number',
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('holder_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('total_amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('payment_interval', models.IntegerField(choices=[(1, 'Monthly'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year')])),
                ('policy_years', models.IntegerField()),
                ('next_due_date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
    ]
